version: "3.9"
services:
  app:
    build: .
    container_name: sms_app
    environment:
      - API_KEY=${API_KEY}
      - DATABASE_URL=${DATABASE_URL:-sqlite+aiosqlite:///sms_database.db}
    volumes:
      - ./:/app
      - sms_db:/app/sms_database.db
    expose:
      - "8000"

  nginx:
    image: nginx:1.25-alpine
    container_name: sms_nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  sms_db:
